apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: api-mock
  name: api-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-mock
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: api-mock
    spec:
      containers:
      - image: longhar/api-mock
        imagePullPolicy: ""
        name: api-mock
        ports:
        - containerPort: 4010
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
