version: "3.7"
services:
    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: swagger-ui
        depends_on:
          - api-mock
        environment:
          - SWAGGER_JSON=/foo/openapi.yaml
        ports:
          - 8246:8080
        volumes:
          - ./:/foo

    api-mock:
        image: rubengarciacid/api-mock
        container_name: api-mock
        build: .
        ports:
            - "4010:4010"